"""sync schema

Revision ID: cf27c884b30d
Revises: 7b8e1bbfdf3f
Create Date: 2026-09-29 13:20:27.684462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf27c884b30d'
down_revision = '7b8e1bbfdf3f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
